# Generated by Django 4.0.3 on 2022-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prep', models.IntegerField()),
                ('cook', models.IntegerField()),
                ('yields', models.IntegerField()),
                ('step', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('rate', models.IntegerField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')])),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
