# Generated by Django 4.0.3 on 2022-04-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_ctg_alter_recipe_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('subject', models.CharField(max_length=512)),
                ('message', models.TextField()),
            ],
        ),
    ]
